
/* !!! This is code generated by Prisma. Do not edit directly. !!!
/* eslint-disable */
// biome-ignore-all lint: generated file

Object.defineProperty(exports, "__esModule", { value: true });

const {
  Decimal,
  objectEnumValues,
  makeStrictEnum,
  Public,
  getRuntime,
  skip
} = require('./runtime/index-browser.js')


const Prisma = {}

exports.Prisma = Prisma
exports.$Enums = {}

/**
 * Prisma Client JS version: 6.19.3
 * Query Engine version: c2990dca591cba766e3b7ef5d9e8a84796e47ab7
 */
Prisma.prismaVersion = {
  client: "6.19.3",
  engine: "c2990dca591cba766e3b7ef5d9e8a84796e47ab7"
}

Prisma.PrismaClientKnownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientKnownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)};
Prisma.PrismaClientUnknownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientUnknownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientRustPanicError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientRustPanicError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientInitializationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientInitializationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientValidationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientValidationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.Decimal = Decimal

/**
 * Re-export of sql-template-tag
 */
Prisma.sql = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`sqltag is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.empty = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`empty is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.join = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`join is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.raw = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`raw is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.validator = Public.validator

/**
* Extensions
*/
Prisma.getExtensionContext = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.getExtensionContext is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.defineExtension = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.defineExtension is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}

/**
 * Shorthand utilities for JSON filtering
 */
Prisma.DbNull = objectEnumValues.instances.DbNull
Prisma.JsonNull = objectEnumValues.instances.JsonNull
Prisma.AnyNull = objectEnumValues.instances.AnyNull

Prisma.NullTypes = {
  DbNull: objectEnumValues.classes.DbNull,
  JsonNull: objectEnumValues.classes.JsonNull,
  AnyNull: objectEnumValues.classes.AnyNull
}



/**
 * Enums
 */

exports.Prisma.TransactionIsolationLevel = makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
});

exports.Prisma.UserScalarFieldEnum = {
  id: 'id',
  walletAddress: 'walletAddress',
  email: 'email',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.MarketScalarFieldEnum = {
  id: 'id',
  question: 'question',
  category: 'category',
  status: 'status',
  settlementCurrency: 'settlementCurrency',
  initialYesProb: 'initialYesProb',
  currentYesProb: 'currentYesProb',
  confidenceInterval: 'confidenceInterval',
  expiryTimestamp: 'expiryTimestamp',
  resolutionOracle: 'resolutionOracle',
  minimumLiquidity: 'minimumLiquidity',
  totalLiquidity: 'totalLiquidity',
  onChainAddress: 'onChainAddress',
  txHash: 'txHash',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.TradeScalarFieldEnum = {
  id: 'id',
  marketId: 'marketId',
  direction: 'direction',
  status: 'status',
  amount: 'amount',
  price: 'price',
  edgeDetected: 'edgeDetected',
  kellyFraction: 'kellyFraction',
  txHash: 'txHash',
  builderFee: 'builderFee',
  errorMessage: 'errorMessage',
  executedAt: 'executedAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.PositionScalarFieldEnum = {
  id: 'id',
  marketId: 'marketId',
  tradeId: 'tradeId',
  direction: 'direction',
  status: 'status',
  entryPrice: 'entryPrice',
  currentPrice: 'currentPrice',
  size: 'size',
  pnl: 'pnl',
  hedgeMarketId: 'hedgeMarketId',
  closedAt: 'closedAt',
  closeReason: 'closeReason',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.ReasoningTraceScalarFieldEnum = {
  id: 'id',
  marketId: 'marketId',
  agentType: 'agentType',
  decisionType: 'decisionType',
  sourcesUsed: 'sourcesUsed',
  probabilityEstimate: 'probabilityEstimate',
  marketProbability: 'marketProbability',
  edge: 'edge',
  confidenceInterval: 'confidenceInterval',
  betFraction: 'betFraction',
  betSizeUsdc: 'betSizeUsdc',
  hedgeConditions: 'hedgeConditions',
  agentWallet: 'agentWallet',
  signature: 'signature',
  ipfsCid: 'ipfsCid',
  sha256Hash: 'sha256Hash',
  onChainTxHash: 'onChainTxHash',
  verified: 'verified',
  isPublic: 'isPublic',
  previewSources: 'previewSources',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.CopyTradeScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  traceId: 'traceId',
  marketId: 'marketId',
  tradeId: 'tradeId',
  direction: 'direction',
  amount: 'amount',
  txHash: 'txHash',
  builderFee: 'builderFee',
  status: 'status',
  pnl: 'pnl',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.SubscriptionScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  traceId: 'traceId',
  type: 'type',
  status: 'status',
  amountPaid: 'amountPaid',
  currency: 'currency',
  txHash: 'txHash',
  expiresAt: 'expiresAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.AgentLogScalarFieldEnum = {
  id: 'id',
  agentType: 'agentType',
  level: 'level',
  action: 'action',
  marketId: 'marketId',
  data: 'data',
  error: 'error',
  createdAt: 'createdAt'
};

exports.Prisma.SignalCacheScalarFieldEnum = {
  id: 'id',
  source: 'source',
  payload: 'payload',
  fetchedAt: 'fetchedAt',
  expiresAt: 'expiresAt'
};

exports.Prisma.BlockIndexScalarFieldEnum = {
  id: 'id',
  chainId: 'chainId',
  lastBlockNumber: 'lastBlockNumber',
  updatedAt: 'updatedAt'
};

exports.Prisma.SortOrder = {
  asc: 'asc',
  desc: 'desc'
};

exports.Prisma.JsonNullValueInput = {
  JsonNull: Prisma.JsonNull
};

exports.Prisma.NullableJsonNullValueInput = {
  DbNull: Prisma.DbNull,
  JsonNull: Prisma.JsonNull
};

exports.Prisma.QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
};

exports.Prisma.NullsOrder = {
  first: 'first',
  last: 'last'
};

exports.Prisma.JsonNullValueFilter = {
  DbNull: Prisma.DbNull,
  JsonNull: Prisma.JsonNull,
  AnyNull: Prisma.AnyNull
};
exports.MarketCategory = exports.$Enums.MarketCategory = {
  FED: 'FED',
  ECB: 'ECB',
  ELECTION: 'ELECTION',
  GEOPOLITICAL: 'GEOPOLITICAL',
  CRYPTO: 'CRYPTO',
  MACRO: 'MACRO'
};

exports.MarketStatus = exports.$Enums.MarketStatus = {
  PENDING: 'PENDING',
  ACTIVE: 'ACTIVE',
  RESOLVING: 'RESOLVING',
  RESOLVED: 'RESOLVED',
  CANCELLED: 'CANCELLED'
};

exports.SettlementCurrency = exports.$Enums.SettlementCurrency = {
  USDC: 'USDC',
  EURC: 'EURC'
};

exports.TradeDirection = exports.$Enums.TradeDirection = {
  YES: 'YES',
  NO: 'NO'
};

exports.TradeStatus = exports.$Enums.TradeStatus = {
  PENDING: 'PENDING',
  EXECUTED: 'EXECUTED',
  FAILED: 'FAILED',
  CANCELLED: 'CANCELLED'
};

exports.PositionStatus = exports.$Enums.PositionStatus = {
  OPEN: 'OPEN',
  CLOSED: 'CLOSED',
  HEDGED: 'HEDGED',
  STOP_LOSS: 'STOP_LOSS'
};

exports.AgentType = exports.$Enums.AgentType = {
  MARKET_MAKER: 'MARKET_MAKER',
  TRADER: 'TRADER'
};

exports.SubscriptionType = exports.$Enums.SubscriptionType = {
  PER_TRACE: 'PER_TRACE',
  DAILY_PASS: 'DAILY_PASS'
};

exports.SubscriptionStatus = exports.$Enums.SubscriptionStatus = {
  ACTIVE: 'ACTIVE',
  EXPIRED: 'EXPIRED',
  CANCELLED: 'CANCELLED'
};

exports.LogLevel = exports.$Enums.LogLevel = {
  INFO: 'INFO',
  WARN: 'WARN',
  ERROR: 'ERROR',
  DEBUG: 'DEBUG'
};

exports.Prisma.ModelName = {
  User: 'User',
  Market: 'Market',
  Trade: 'Trade',
  Position: 'Position',
  ReasoningTrace: 'ReasoningTrace',
  CopyTrade: 'CopyTrade',
  Subscription: 'Subscription',
  AgentLog: 'AgentLog',
  SignalCache: 'SignalCache',
  BlockIndex: 'BlockIndex'
};

/**
 * This is a stub Prisma Client that will error at runtime if called.
 */
class PrismaClient {
  constructor() {
    return new Proxy(this, {
      get(target, prop) {
        let message
        const runtime = getRuntime()
        if (runtime.isEdge) {
          message = `PrismaClient is not configured to run in ${runtime.prettyName}. In order to run Prisma Client on edge runtime, either:
- Use Prisma Accelerate: https://pris.ly/d/accelerate
- Use Driver Adapters: https://pris.ly/d/driver-adapters
`;
        } else {
          message = 'PrismaClient is unable to run in this browser environment, or has been bundled for the browser (running in `' + runtime.prettyName + '`).'
        }

        message += `
If this is unexpected, please open an issue: https://pris.ly/prisma-prisma-bug-report`

        throw new Error(message)
      }
    })
  }
}

exports.PrismaClient = PrismaClient

Object.assign(exports, Prisma)
